package com.mybank.pc.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardBin<M extends BaseCardBin<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setBankName(String bankName) {
		set("bankName", bankName);
	}
	
	public String getBankName() {
		return getStr("bankName");
	}

	public void setCardName(String cardName) {
		set("cardName", cardName);
	}
	
	public String getCardName() {
		return getStr("cardName");
	}

	public void setCBin(String cBin) {
		set("cBin", cBin);
	}
	
	public String getCBin() {
		return getStr("cBin");
	}

	public void setCardType(String cardType) {
		set("cardType", cardType);
	}
	
	public String getCardType() {
		return getStr("cardType");
	}

}
