package com.mybank.pc.merchant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchantCust<M extends BaseMerchantCust<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMerID(java.lang.Integer merID) {
		set("merID", merID);
	}
	
	public java.lang.Integer getMerID() {
		return getInt("merID");
	}

	public void setMerNo(java.lang.String merNo) {
		set("merNo", merNo);
	}
	
	public java.lang.String getMerNo() {
		return getStr("merNo");
	}

	public void setCustName(java.lang.String custName) {
		set("custName", custName);
	}
	
	public java.lang.String getCustName() {
		return getStr("custName");
	}

	public void setCardID(java.lang.String cardID) {
		set("cardID", cardID);
	}
	
	public java.lang.String getCardID() {
		return getStr("cardID");
	}

	public void setMobileBank(java.lang.String mobileBank) {
		set("mobileBank", mobileBank);
	}
	
	public java.lang.String getMobileBank() {
		return getStr("mobileBank");
	}

	public void setBankcardNo(java.lang.String bankcardNo) {
		set("bankcardNo", bankcardNo);
	}
	
	public java.lang.String getBankcardNo() {
		return getStr("bankcardNo");
	}

	public void setCardImgZ(java.lang.String cardImgZ) {
		set("cardImgZ", cardImgZ);
	}
	
	public java.lang.String getCardImgZ() {
		return getStr("cardImgZ");
	}


	public void setSelfImg(java.lang.String selfImg) {
		set("selfImg", selfImg);
	}

	public java.lang.String getSelfImg() {
		return getStr("selfImg");
	}

	public void setAuthImg(java.lang.String authImg) {
		set("authImg", authImg);
	}

	public java.lang.String getAuthImg() {
		return getStr("authImg");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}
	
	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
