package com.mybank.pc.merchant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchantFee<M extends BaseMerchantFee<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMerID(java.lang.Integer merID) {
		set("merID", merID);
	}
	
	public java.lang.Integer getMerID() {
		return getInt("merID");
	}

	public void setTradeType(java.lang.String tradeType) {
		set("tradeType", tradeType);
	}
	
	public java.lang.String getTradeType() {
		return getStr("tradeType");
	}

	public void setAmountLower(java.math.BigDecimal amountLower) {
		set("amountLower", amountLower);
	}
	
	public java.math.BigDecimal getAmountLower() {
		return get("amountLower");
	}

	public void setAmountUpper(java.math.BigDecimal amountUpper) {
		set("amountUpper", amountUpper);
	}
	
	public java.math.BigDecimal getAmountUpper() {
		return get("amountUpper");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setRatio(java.math.BigDecimal ratio) {
		set("ratio", ratio);
	}
	
	public java.math.BigDecimal getRatio() {
		return get("ratio");
	}

	public void setFeeType(java.lang.String feeType) {
		set("feeType", feeType);
	}
	
	public java.lang.String getFeeType() {
		return getStr("feeType");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}
	
	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
