package com.mybank.pc.merchant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchantAmountLog<M extends BaseMerchantAmountLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setMerID(Integer merID) {
		set("merID", merID);
	}
	
	public Integer getMerID() {
		return getInt("merID");
	}

	public void setMerNo(String merNo) {
		set("merNo", merNo);
	}
	
	public String getMerNo() {
		return getStr("merNo");
	}

	public void setMerName(String merName) {
		set("merName", merName);
	}
	
	public String getMerName() {
		return getStr("merName");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setTAmount(java.math.BigDecimal tAmount) {
		set("tAmount", tAmount);
	}
	
	public java.math.BigDecimal getTAmount() {
		return get("tAmount");
	}

	public void setAmountType(String amountType) {
		set("amountType", amountType);
	}
	
	public String getAmountType() {
		return getStr("amountType");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(String operID) {
		set("operID", operID);
	}
	
	public String getOperID() {
		return getStr("operID");
	}

}
