package com.mybank.pc.merchant.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchantFeeAmountRecord<M extends BaseMerchantFeeAmountRecord<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setMerId(Integer merId) {
		set("merId", merId);
	}
	
	public Integer getMerId() {
		return getInt("merId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setBAmount(java.math.BigDecimal bAmount) {
		set("bAmount", bAmount);
	}
	
	public java.math.BigDecimal getBAmount() {
		return get("bAmount");
	}

	public void setAAmount(java.math.BigDecimal aAmount) {
		set("aAmount", aAmount);
	}
	
	public java.math.BigDecimal getAAmount() {
		return get("aAmount");
	}

	public void setMerName(String merName) {
		set("merName", merName);
	}
	
	public String getMerName() {
		return getStr("merName");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

	public void setOperId(Integer operId) {
		set("operId", operId);
	}
	
	public Integer getOperId() {
		return getInt("operId");
	}

	public void setMerNo(java.lang.String merNo) {
		set("merNo", merNo);
	}

	public java.lang.String getMerNo() {
		return getStr("merNo");
	}

	public void setOperName(java.lang.String operName) {
		set("operName", operName);
	}

	public java.lang.String getOperName() {
		return getStr("operName");
	}

	public void setRemark(String remark){
		set("remark",remark);
	}
	public String getRemark(){
		return getStr("remark");
	}

}
