package com.mybank.pc.merchant.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchantUser<M extends BaseMerchantUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setMerchantID(Integer merchantID) {
		set("merchantID", merchantID);
	}
	
	public Integer getMerchantID() {
		return getInt("merchantID");
	}

	public void setUserID(Integer userID) {
		set("userID", userID);
	}
	
	public Integer getUserID() {
		return getInt("userID");
	}

	public abstract String getTableName();
}
