package com.mybank.pc.admin.model;


import com.mybank.pc.admin.model.base.BaseCardBin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardBin extends BaseCardBin<CardBin> {
	public static final CardBin dao = new CardBin().dao();
}
