package com.mybank.pc.admin.model;


import com.mybank.pc.admin.model.base.BaseLogOp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOp extends BaseLogOp<LogOp> {
	public static final LogOp dao = new LogOp().dao();
}
