package com.mybank.pc.admin.model;


import com.mybank.pc.admin.model.base.BaseUfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ufile extends BaseUfile<Ufile> {
	public static final Ufile dao = new Ufile().dao();
}
