package com.mybank.pc.merchant.model;

import com.mybank.pc.kits.DateKit;
import com.mybank.pc.kits.FeeKit;
import com.mybank.pc.merchant.model.base.BaseMerchantCust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantCust extends BaseMerchantCust<MerchantCust> {
	public static final MerchantCust dao = new MerchantCust().dao();

	public String getCatTxt() {
		return DateKit.dateToStr(getCat(), "yyyy-MM-dd HH:mm:ss");
	}

	public MerchantInfo getMerchantInfo() {
		return MerchantInfo.dao.findById(getMerID());
	}



}
