package com.mybank.pc.merchant.model;


import com.mybank.pc.merchant.model.base.BaseMerchantAmountLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantAmountLog extends BaseMerchantAmountLog<MerchantAmountLog> {
	public static final MerchantAmountLog dao = new MerchantAmountLog().dao();
}
