package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseMerchantUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantUser extends BaseMerchantUser<MerchantUser> {
	public static final MerchantUser dao = new MerchantUser().dao();

	@Override
	public String getTableName() {
		return "merchant_user";
	}
}
