package com.mybank.pc.merchant.model;

import com.jfinal.plugin.ehcache.CacheKit;
import com.mybank.pc.Consts;
import com.mybank.pc.admin.model.Taxonomy;
import com.mybank.pc.kits.DateKit;
import com.mybank.pc.merchant.model.base.BaseMerchantInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantInfo extends BaseMerchantInfo<MerchantInfo> {
	public static final MerchantInfo dao = new MerchantInfo().dao();

	public String getStatusTxt(){
		String sts = getStatus();
		if(sts==null)return "";
		if("0".equals(sts)){
			return "正常";
		}
		else if("1".equals(sts)){
			return "禁用";
		}else {
			return "";
		}


	}
	public String getMerTypeTxt(){
		String ts = getMerchantType();
		if(ts==null)return "";
		List<Taxonomy>  list=CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),"merTypeList");
		for (Taxonomy t :list){
			if(t.getText().equals(ts)){
				return t.getTitle();
			}

		}
			return "";
	}
	public String getCatTxt(){
		return DateKit.dateToStr(getCat(),DateKit.yyyy_MM_dd);
	}
}
