package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseMerchantFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantFee extends BaseMerchantFee<MerchantFee> {
	public static final MerchantFee dao = new MerchantFee().dao();
}
