package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnionpayEntrust<M extends BaseUnionpayEntrust<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setCustomerNm(java.lang.String customerNm) {
		set("customerNm", customerNm);
	}
	
	public java.lang.String getCustomerNm() {
		return getStr("customerNm");
	}

	public void setCertifTp(java.lang.String certifTp) {
		set("certifTp", certifTp);
	}
	
	public java.lang.String getCertifTp() {
		return getStr("certifTp");
	}

	public void setCertifId(java.lang.String certifId) {
		set("certifId", certifId);
	}
	
	public java.lang.String getCertifId() {
		return getStr("certifId");
	}

	public void setAccNo(java.lang.String accNo) {
		set("accNo", accNo);
	}
	
	public java.lang.String getAccNo() {
		return getStr("accNo");
	}

	public void setPhoneNo(java.lang.String phoneNo) {
		set("phoneNo", phoneNo);
	}
	
	public java.lang.String getPhoneNo() {
		return getStr("phoneNo");
	}

	public void setCvn2(java.lang.String cvn2) {
		set("cvn2", cvn2);
	}
	
	public java.lang.String getCvn2() {
		return getStr("cvn2");
	}

	public void setExpired(java.lang.String expired) {
		set("expired", expired);
	}
	
	public java.lang.String getExpired() {
		return getStr("expired");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("tradeNo", tradeNo);
	}
	
	public java.lang.String getTradeNo() {
		return getStr("tradeNo");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

	public void setTxnType(java.lang.String txnType) {
		set("txnType", txnType);
	}
	
	public java.lang.String getTxnType() {
		return getStr("txnType");
	}

	public void setTxnSubType(java.lang.String txnSubType) {
		set("txnSubType", txnSubType);
	}
	
	public java.lang.String getTxnSubType() {
		return getStr("txnSubType");
	}

	public void setBizType(java.lang.String bizType) {
		set("bizType", bizType);
	}
	
	public java.lang.String getBizType() {
		return getStr("bizType");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setAccessType(java.lang.String accessType) {
		set("accessType", accessType);
	}
	
	public java.lang.String getAccessType() {
		return getStr("accessType");
	}

	public void setAccType(java.lang.String accType) {
		set("accType", accType);
	}
	
	public java.lang.String getAccType() {
		return getStr("accType");
	}

	public void setTxnTime(java.lang.String txnTime) {
		set("txnTime", txnTime);
	}
	
	public java.lang.String getTxnTime() {
		return getStr("txnTime");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}
	
	public java.lang.String getMerId() {
		return getStr("merId");
	}

	public void setReq(java.lang.String req) {
		set("req", req);
	}
	
	public java.lang.String getReq() {
		return getStr("req");
	}

	public void setRespCode(java.lang.String respCode) {
		set("respCode", respCode);
	}
	
	public java.lang.String getRespCode() {
		return getStr("respCode");
	}

	public void setRespMsg(java.lang.String respMsg) {
		set("respMsg", respMsg);
	}
	
	public java.lang.String getRespMsg() {
		return getStr("respMsg");
	}

	public void setResp(java.lang.String resp) {
		set("resp", resp);
	}
	
	public java.lang.String getResp() {
		return getStr("resp");
	}

	public void setMerchantID(java.lang.String merchantID) {
		set("merchantID", merchantID);
	}
	
	public java.lang.String getMerchantID() {
		return getStr("merchantID");
	}

	public void setFinalCode(java.lang.String finalCode) {
		set("finalCode", finalCode);
	}
	
	public java.lang.String getFinalCode() {
		return getStr("finalCode");
	}

	public void setExceInfo(java.lang.String exceInfo) {
		set("exceInfo", exceInfo);
	}
	
	public java.lang.String getExceInfo() {
		return getStr("exceInfo");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}
	
	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
