package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnionpayCollectionQuery<M extends BaseUnionpayCollectionQuery<M>> extends Model<M>
		implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPlanId(java.lang.String planId) {
		set("planId", planId);
	}

	public java.lang.String getPlanId() {
		return getStr("planId");
	}

	public void setExecutionId(java.lang.String executionId) {
		set("executionId", executionId);
	}

	public java.lang.String getExecutionId() {
		return getStr("executionId");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setEncoding(java.lang.String encoding) {
		set("encoding", encoding);
	}

	public java.lang.String getEncoding() {
		return getStr("encoding");
	}

	public void setTxnType(java.lang.String txnType) {
		set("txnType", txnType);
	}

	public java.lang.String getTxnType() {
		return getStr("txnType");
	}

	public void setTxnSubType(java.lang.String txnSubType) {
		set("txnSubType", txnSubType);
	}

	public java.lang.String getTxnSubType() {
		return getStr("txnSubType");
	}

	public void setOrigTxnType(java.lang.String origTxnType) {
		set("origTxnType", origTxnType);
	}

	public java.lang.String getOrigTxnType() {
		return getStr("origTxnType");
	}

	public void setOrigTxnSubType(java.lang.String origTxnSubType) {
		set("origTxnSubType", origTxnSubType);
	}

	public java.lang.String getOrigTxnSubType() {
		return getStr("origTxnSubType");
	}

	public void setBizType(java.lang.String bizType) {
		set("bizType", bizType);
	}

	public java.lang.String getBizType() {
		return getStr("bizType");
	}

	public void setAccessType(java.lang.String accessType) {
		set("accessType", accessType);
	}

	public java.lang.String getAccessType() {
		return getStr("accessType");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}

	public java.lang.String getMerId() {
		return getStr("merId");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}

	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}

	public void setTxnTime(java.lang.String txnTime) {
		set("txnTime", txnTime);
	}

	public java.lang.String getTxnTime() {
		return getStr("txnTime");
	}

	public void setAcqInsCode(java.lang.String acqInsCode) {
		set("acqInsCode", acqInsCode);
	}

	public java.lang.String getAcqInsCode() {
		return getStr("acqInsCode");
	}

	public void setReserved(java.lang.String reserved) {
		set("reserved", reserved);
	}

	public java.lang.String getReserved() {
		return getStr("reserved");
	}

	public void setQueryId(java.lang.String queryId) {
		set("queryId", queryId);
	}

	public java.lang.String getQueryId() {
		return getStr("queryId");
	}

	public void setTraceNo(java.lang.String traceNo) {
		set("traceNo", traceNo);
	}

	public java.lang.String getTraceNo() {
		return getStr("traceNo");
	}

	public void setTraceTime(java.lang.String traceTime) {
		set("traceTime", traceTime);
	}

	public java.lang.String getTraceTime() {
		return getStr("traceTime");
	}

	public void setSettleAmt(java.lang.String settleAmt) {
		set("settleAmt", settleAmt);
	}

	public java.lang.String getSettleAmt() {
		return getStr("settleAmt");
	}

	public void setSettleCurrencyCode(java.lang.String settleCurrencyCode) {
		set("settleCurrencyCode", settleCurrencyCode);
	}

	public java.lang.String getSettleCurrencyCode() {
		return getStr("settleCurrencyCode");
	}

	public void setSettleDate(java.lang.String settleDate) {
		set("settleDate", settleDate);
	}

	public java.lang.String getSettleDate() {
		return getStr("settleDate");
	}

	public void setExchangeRate(java.lang.String exchangeRate) {
		set("exchangeRate", exchangeRate);
	}

	public java.lang.String getExchangeRate() {
		return getStr("exchangeRate");
	}

	public void setExchangeDate(java.lang.String exchangeDate) {
		set("exchangeDate", exchangeDate);
	}

	public java.lang.String getExchangeDate() {
		return getStr("exchangeDate");
	}

	public void setCurrencyCode(java.lang.String currencyCode) {
		set("currencyCode", currencyCode);
	}

	public java.lang.String getCurrencyCode() {
		return getStr("currencyCode");
	}

	public void setTxnAmt(java.lang.String txnAmt) {
		set("txnAmt", txnAmt);
	}

	public java.lang.String getTxnAmt() {
		return getStr("txnAmt");
	}

	public void setOrigRespCode(java.lang.String origRespCode) {
		set("origRespCode", origRespCode);
	}

	public java.lang.String getOrigRespCode() {
		return getStr("origRespCode");
	}

	public void setOrigRespMsg(java.lang.String origRespMsg) {
		set("origRespMsg", origRespMsg);
	}

	public java.lang.String getOrigRespMsg() {
		return getStr("origRespMsg");
	}

	public void setAccNo(java.lang.String accNo) {
		set("accNo", accNo);
	}

	public java.lang.String getAccNo() {
		return getStr("accNo");
	}

	public void setPayCardType(java.lang.String payCardType) {
		set("payCardType", payCardType);
	}

	public java.lang.String getPayCardType() {
		return getStr("payCardType");
	}

	public void setPayType(java.lang.String payType) {
		set("payType", payType);
	}

	public java.lang.String getPayType() {
		return getStr("payType");
	}

	public void setPayCardNo(java.lang.String payCardNo) {
		set("payCardNo", payCardNo);
	}

	public java.lang.String getPayCardNo() {
		return getStr("payCardNo");
	}

	public void setPayCardIssueName(java.lang.String payCardIssueName) {
		set("payCardIssueName", payCardIssueName);
	}

	public java.lang.String getPayCardIssueName() {
		return getStr("payCardIssueName");
	}

	public void setCardTransData(java.lang.String cardTransData) {
		set("cardTransData", cardTransData);
	}

	public java.lang.String getCardTransData() {
		return getStr("cardTransData");
	}

	public void setIssuerIdentifyMode(java.lang.String issuerIdentifyMode) {
		set("issuerIdentifyMode", issuerIdentifyMode);
	}

	public java.lang.String getIssuerIdentifyMode() {
		return getStr("issuerIdentifyMode");
	}

	public void setMerchantID(java.lang.String merchantID) {
		set("merchantID", merchantID);
	}

	public java.lang.String getMerchantID() {
		return getStr("merchantID");
	}

	public void setReqReserved(java.lang.String reqReserved) {
		set("reqReserved", reqReserved);
	}

	public java.lang.String getReqReserved() {
		return getStr("reqReserved");
	}

	public void setReq(java.lang.String req) {
		set("req", req);
	}

	public java.lang.String getReq() {
		return getStr("req");
	}

	public void setRespCode(java.lang.String respCode) {
		set("respCode", respCode);
	}

	public java.lang.String getRespCode() {
		return getStr("respCode");
	}

	public void setRespMsg(java.lang.String respMsg) {
		set("respMsg", respMsg);
	}

	public java.lang.String getRespMsg() {
		return getStr("respMsg");
	}

	public void setResp(java.lang.String resp) {
		set("resp", resp);
	}

	public java.lang.String getResp() {
		return getStr("resp");
	}

	public void setExceInfo(java.lang.String exceInfo) {
		set("exceInfo", exceInfo);
	}

	public java.lang.String getExceInfo() {
		return getStr("exceInfo");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}

	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}

	public java.util.Date getMat() {
		return get("mat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}

	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
