package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnionpayCallbackLog<M extends BaseUnionpayCallbackLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInfo(java.lang.String info) {
		set("info", info);
	}

	public java.lang.String getInfo() {
		return getStr("info");
	}

	public void setValidate(java.lang.String validate) {
		set("validate", validate);
	}

	public java.lang.String getValidate() {
		return getStr("validate");
	}

	public void setQueryId(java.lang.String queryId) {
		set("queryId", queryId);
	}

	public java.lang.String getQueryId() {
		return getStr("queryId");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

	public void setRespCode(java.lang.String respCode) {
		set("respCode", respCode);
	}

	public java.lang.String getRespCode() {
		return getStr("respCode");
	}

	public void setRespMsg(java.lang.String respMsg) {
		set("respMsg", respMsg);
	}

	public java.lang.String getRespMsg() {
		return getStr("respMsg");
	}

	public void setSettleAmt(java.lang.String settleAmt) {
		set("settleAmt", settleAmt);
	}

	public java.lang.String getSettleAmt() {
		return getStr("settleAmt");
	}

	public void setSettleCurrencyCode(java.lang.String settleCurrencyCode) {
		set("settleCurrencyCode", settleCurrencyCode);
	}

	public java.lang.String getSettleCurrencyCode() {
		return getStr("settleCurrencyCode");
	}

	public void setSettleDate(java.lang.String settleDate) {
		set("settleDate", settleDate);
	}

	public java.lang.String getSettleDate() {
		return getStr("settleDate");
	}

	public void setTraceNo(java.lang.String traceNo) {
		set("traceNo", traceNo);
	}

	public java.lang.String getTraceNo() {
		return getStr("traceNo");
	}

	public void setTraceTime(java.lang.String traceTime) {
		set("traceTime", traceTime);
	}

	public java.lang.String getTraceTime() {
		return getStr("traceTime");
	}

	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}

	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}

	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}

	public java.lang.String getMerId() {
		return getStr("merId");
	}

	public void setTxnTime(java.lang.String txnTime) {
		set("txnTime", txnTime);
	}

	public java.lang.String getTxnTime() {
		return getStr("txnTime");
	}

	public void setTxnType(java.lang.String txnType) {
		set("txnType", txnType);
	}

	public java.lang.String getTxnType() {
		return getStr("txnType");
	}

	public void setTxnSubType(java.lang.String txnSubType) {
		set("txnSubType", txnSubType);
	}

	public java.lang.String getTxnSubType() {
		return getStr("txnSubType");
	}

	public void setTxnAmt(java.lang.String txnAmt) {
		set("txnAmt", txnAmt);
	}

	public java.lang.String getTxnAmt() {
		return getStr("txnAmt");
	}

}
