package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnionpayBatchCollection<M extends BaseUnionpayBatchCollection<M>> extends Model<M>
		implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setEncoding(java.lang.String encoding) {
		set("encoding", encoding);
	}

	public java.lang.String getEncoding() {
		return getStr("encoding");
	}

	public void setTxnType(java.lang.String txnType) {
		set("txnType", txnType);
	}

	public java.lang.String getTxnType() {
		return getStr("txnType");
	}

	public void setTxnSubType(java.lang.String txnSubType) {
		set("txnSubType", txnSubType);
	}

	public java.lang.String getTxnSubType() {
		return getStr("txnSubType");
	}

	public void setBizType(java.lang.String bizType) {
		set("bizType", bizType);
	}

	public java.lang.String getBizType() {
		return getStr("bizType");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}

	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setAccessType(java.lang.String accessType) {
		set("accessType", accessType);
	}

	public java.lang.String getAccessType() {
		return getStr("accessType");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}

	public java.lang.String getMerId() {
		return getStr("merId");
	}

	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}

	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}

	public void setTxnTime(java.lang.String txnTime) {
		set("txnTime", txnTime);
	}

	public java.lang.String getTxnTime() {
		return getStr("txnTime");
	}

	public void setTotalQty(java.lang.String totalQty) {
		set("totalQty", totalQty);
	}

	public java.lang.String getTotalQty() {
		return getStr("totalQty");
	}

	public void setTotalAmt(java.lang.String totalAmt) {
		set("totalAmt", totalAmt);
	}

	public java.lang.String getTotalAmt() {
		return getStr("totalAmt");
	}

	public void setRequestFileContent(java.lang.String requestFileContent) {
		set("requestFileContent", requestFileContent);
	}

	public java.lang.String getRequestFileContent() {
		return getStr("requestFileContent");
	}

	public void setReqReserved(java.lang.String reqReserved) {
		set("reqReserved", reqReserved);
	}

	public java.lang.String getReqReserved() {
		return getStr("reqReserved");
	}

	public void setReqReserved1(java.lang.String reqReserved1) {
		set("reqReserved1", reqReserved1);
	}

	public java.lang.String getReqReserved1() {
		return getStr("reqReserved1");
	}

	public void setReqReserved2(java.lang.String reqReserved2) {
		set("reqReserved2", reqReserved2);
	}

	public java.lang.String getReqReserved2() {
		return getStr("reqReserved2");
	}

	public void setReq(java.lang.String req) {
		set("req", req);
	}

	public java.lang.String getReq() {
		return getStr("req");
	}

	public void setRespCode(java.lang.String respCode) {
		set("respCode", respCode);
	}

	public java.lang.String getRespCode() {
		return getStr("respCode");
	}

	public void setRespMsg(java.lang.String respMsg) {
		set("respMsg", respMsg);
	}

	public java.lang.String getRespMsg() {
		return getStr("respMsg");
	}

	public void setResp(java.lang.String resp) {
		set("resp", resp);
	}

	public java.lang.String getResp() {
		return getStr("resp");
	}

	public void setResultCode(java.lang.String resultCode) {
		set("resultCode", resultCode);
	}

	public java.lang.String getResultCode() {
		return getStr("resultCode");
	}

	public void setResultMsg(java.lang.String resultMsg) {
		set("resultMsg", resultMsg);
	}

	public java.lang.String getResultMsg() {
		return getStr("resultMsg");
	}

	public void setResultFileContent(java.lang.String resultFileContent) {
		set("resultFileContent", resultFileContent);
	}

	public java.lang.String getResultFileContent() {
		return getStr("resultFileContent");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return getStr("result");
	}

	public void setFinalCode(java.lang.String finalCode) {
		set("finalCode", finalCode);
	}

	public java.lang.String getFinalCode() {
		return getStr("finalCode");
	}

	public void setSuccessAmt(java.lang.String successAmt) {
		set("successAmt", successAmt);
	}

	public java.lang.String getSuccessAmt() {
		return getStr("successAmt");
	}

	public void setSuccessQty(java.lang.String successQty) {
		set("successQty", successQty);
	}

	public java.lang.String getSuccessQty() {
		return getStr("successQty");
	}

	public void setExceInfo(java.lang.String exceInfo) {
		set("exceInfo", exceInfo);
	}

	public java.lang.String getExceInfo() {
		return getStr("exceInfo");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setSysQueryId(java.lang.String sysQueryId) {
		set("sysQueryId", sysQueryId);
	}

	public java.lang.String getSysQueryId() {
		return getStr("sysQueryId");
	}

	public void setQueryResultCount(java.lang.Integer queryResultCount) {
		set("queryResultCount", queryResultCount);
	}

	public java.lang.Integer getQueryResultCount() {
		return getInt("queryResultCount");
	}

	public void setNextQueryTime(java.util.Date nextQueryTime) {
		set("nextQueryTime", nextQueryTime);
	}

	public java.util.Date getNextQueryTime() {
		return get("nextQueryTime");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}

	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}

	public java.util.Date getMat() {
		return get("mat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}

	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
