package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollectionEntrust<M extends BaseCollectionEntrust<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustomerNm(java.lang.String customerNm) {
		set("customerNm", customerNm);
	}

	public java.lang.String getCustomerNm() {
		return getStr("customerNm");
	}

	public void setCertifTp(java.lang.String certifTp) {
		set("certifTp", certifTp);
	}

	public java.lang.String getCertifTp() {
		return getStr("certifTp");
	}

	public void setCertifId(java.lang.String certifId) {
		set("certifId", certifId);
	}

	public java.lang.String getCertifId() {
		return getStr("certifId");
	}

	public void setAccNo(java.lang.String accNo) {
		set("accNo", accNo);
	}

	public java.lang.String getAccNo() {
		return getStr("accNo");
	}

	public void setPhoneNo(java.lang.String phoneNo) {
		set("phoneNo", phoneNo);
	}

	public java.lang.String getPhoneNo() {
		return getStr("phoneNo");
	}

	public void setCvn2(java.lang.String cvn2) {
		set("cvn2", cvn2);
	}

	public java.lang.String getCvn2() {
		return getStr("cvn2");
	}

	public void setExpired(java.lang.String expired) {
		set("expired", expired);
	}

	public java.lang.String getExpired() {
		return getStr("expired");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}

	public java.lang.String getMerId() {
		return getStr("merId");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}

	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}

	public java.util.Date getMat() {
		return get("mat");
	}

	public void setOperID(java.lang.String operID) {
		set("operID", operID);
	}

	public java.lang.String getOperID() {
		return getStr("operID");
	}

}
