package com.mybank.pc.collection.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnionpayBatchCollectionBatchno<M extends BaseUnionpayBatchCollectionBatchno<M>>
		extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTxnDate(java.lang.String txnDate) {
		set("txnDate", txnDate);
	}

	public java.lang.String getTxnDate() {
		return getStr("txnDate");
	}

	public void setBatchNo(java.lang.Integer batchNo) {
		set("batchNo", batchNo);
	}

	public java.lang.Integer getBatchNo() {
		return getInt("batchNo");
	}

	public void setMerId(java.lang.String merId) {
		set("merId", merId);
	}

	public java.lang.String getMerId() {
		return getStr("merId");
	}

}
