package com.mybank.pc.qrcode.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrcodeInfo<M extends BaseQrcodeInfo<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setWxAcctID(Integer wxAcctID) {
		set("wxAcctID", wxAcctID);
	}
	
	public Integer getWxAcctID() {
		return getInt("wxAcctID");
	}

	public void setQrcodeNo(String qrcodeNo) {
		set("qrcodeNo", qrcodeNo);
	}
	
	public String getQrcodeNo() {
		return getStr("qrcodeNo");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setIsLock(String isLock) {
		set("isLock", isLock);
	}
	
	public String getIsLock() {
		return getStr("isLock");
	}

	public void setIsVail(String isVail) {
		set("isVail", isVail);
	}
	
	public String getIsVail() {
		return getStr("isVail");
	}

	public void setImgName(String imgName) {
		set("imgName", imgName);
	}
	
	public String getImgName() {
		return getStr("imgName");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(String operID) {
		set("operID", operID);
	}
	
	public String getOperID() {
		return getStr("operID");
	}

	public void setWxAcct(String wxAcct) {
		set("wxAcct", wxAcct);
	}

	public String getWxAcct() {
		return getStr("wxAcct");
	}

}
