package com.mybank.pc.qrcode.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrcodeWxacct<M extends BaseQrcodeWxacct<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setWxAcct(String wxAcct) {
		set("wxAcct", wxAcct);
	}
	
	public String getWxAcct() {
		return getStr("wxAcct");
	}

	public void setIsLogin(String isLogin) {
		set("isLogin", isLogin);
	}
	
	public String getIsLogin() {
		return getStr("isLogin");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(String operID) {
		set("operID", operID);
	}
	
	public String getOperID() {
		return getStr("operID");
	}

}
