package com.mybank.pc.trade.model;


import com.mybank.pc.trade.model.base.BaseTradeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TradeLog extends BaseTradeLog<TradeLog> {
	public static final TradeLog dao = new TradeLog().dao();
}
