package com.mybank.pc.qrcode.model;

import com.jfinal.plugin.ehcache.CacheKit;
import com.mybank.pc.Consts;
import com.mybank.pc.admin.model.Taxonomy;
import com.mybank.pc.kits.DateKit;
import com.mybank.pc.qrcode.model.base.BaseQrcodeWxacct;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrcodeWxacct extends BaseQrcodeWxacct<QrcodeWxacct> {
	public static final QrcodeWxacct dao = new QrcodeWxacct().dao();

	public String getIsLoginTxt(){
		String sts = getIsLogin();
		if(sts==null)return "";
		if("0".equals(sts)){
			return "已登录";
		}
		else if("1".equals(sts)){
			return "未登录";
		}else {
			return "";
		}


	}

	public String getCatTxt(){
		return DateKit.dateToStr(getCat(),DateKit.yyyy_MM_dd);
	}
}
