package com.mybank.pc.qrcode.model;

import com.mybank.pc.qrcode.model.base.BaseQrcodeInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrcodeInfo extends BaseQrcodeInfo<QrcodeInfo> {
	public static final QrcodeInfo dao = new QrcodeInfo().dao();
}
