package com.mybank.pc.trade.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTradeLog<M extends BaseTradeLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setTradeNo(String tradeNo) {
		set("tradeNo", tradeNo);
	}
	
	public String getTradeNo() {
		return getStr("tradeNo");
	}

	public void setTradeMerID(Integer tradeMerID) {
		set("tradeMerID", tradeMerID);
	}
	
	public Integer getTradeMerID() {
		return getInt("tradeMerID");
	}

	public void setTradeMerNo(String tradeMerNo) {
		set("tradeMerNo", tradeMerNo);
	}
	
	public String getTradeMerNo() {
		return getStr("tradeMerNo");
	}

	public void setTradeMerName(String tradeMerName) {
		set("tradeMerName", tradeMerName);
	}
	
	public String getTradeMerName() {
		return getStr("tradeMerName");
	}

	public void setTradeTime(java.util.Date tradeTime) {
		set("tradeTime", tradeTime);
	}
	
	public java.util.Date getTradeTime() {
		return get("tradeTime");
	}

	public void setTradeAmount(java.math.BigDecimal tradeAmount) {
		set("tradeAmount", tradeAmount);
	}
	
	public java.math.BigDecimal getTradeAmount() {
		return get("tradeAmount");
	}

	public void setTradeRealAmount(java.math.BigDecimal tradeRealAmount) {
		set("tradeRealAmount", tradeRealAmount);
	}
	
	public java.math.BigDecimal getTradeRealAmount() {
		return get("tradeRealAmount");
	}

	public void setTradeWxAcct(String tradeWxAcct) {
		set("tradeWxAcct", tradeWxAcct);
	}
	
	public String getTradeWxAcct() {
		return getStr("tradeWxAcct");
	}

	public void setTradeQrcodeImg(String tradeQrcodeImg) {
		set("tradeQrcodeImg", tradeQrcodeImg);
	}
	
	public String getTradeQrcodeImg() {
		return getStr("tradeQrcodeImg");
	}

	public void setTradeStatus(String tradeStatus) {
		set("tradeStatus", tradeStatus);
	}
	
	public String getTradeStatus() {
		return getStr("tradeStatus");
	}

	public void setCallBackUrl(String callBackUrl) {
		set("callBackUrl", callBackUrl);
	}
	
	public String getCallBackUrl() {
		return getStr("callBackUrl");
	}

	public void setReqMsg(String reqMsg) {
		set("reqMsg", reqMsg);
	}
	
	public String getReqMsg() {
		return getStr("reqMsg");
	}

	public void setResMsg(String resMsg) {
		set("resMsg", resMsg);
	}
	
	public String getResMsg() {
		return getStr("resMsg");
	}

	public void setCat(java.util.Date cat) {
		set("cat", cat);
	}
	
	public java.util.Date getCat() {
		return get("cat");
	}

	public void setMat(java.util.Date mat) {
		set("mat", mat);
	}
	
	public java.util.Date getMat() {
		return get("mat");
	}

	public void setDat(java.util.Date dat) {
		set("dat", dat);
	}
	
	public java.util.Date getDat() {
		return get("dat");
	}

	public void setOperID(String operID) {
		set("operID", operID);
	}
	
	public String getOperID() {
		return getStr("operID");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}
	public void setTradeImgName(String tradeImgName) {
		set("tradeImgName", tradeImgName);
	}

	public String getTradeImgName() {
		return getStr("tradeImgName");
	}


}
