package com.mybank.pc.collection.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.SqlPara;
import com.mybank.pc.collection.model.base.BaseCollectionEntrust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionEntrust extends BaseCollectionEntrust<CollectionEntrust> {
	public static final CollectionEntrust dao = new CollectionEntrust().dao();

	public CollectionEntrust findOne() {
		CollectionEntrust result = null;
		try {
			SqlPara sqlPara = Db.getSqlPara("collection_entrust.findOne", _getAttrs());
			result = dao.findFirst(sqlPara);
		} catch (Exception e) {
			e.printStackTrace();
			result = null;
		}
		return result;
	}
}
